language: ruby
install:
script: "./.travis.sh"
rvm:
  - 2.0.0
matrix:
  fast_finish: true
env:
  matrix:
notifications:
  email: false
  irc:
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    channels:
        - "chat.freenode.net#rdo-puppet"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
